name: fridge
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_sign_in: ^5.0.7
  rflutter_alert: ^2.0.4
  searchfield: ^0.5.2
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Medium.ttf
